apiVersion: v1
kind: ConfigMap
metadata:
  name: book-review-config
  namespace: book-review
data:
  NODE_ENV: "production"
  PORT: "5000"
  DB_PORT: "3306"
  DB_DIALECT: "mysql"
  DB_SSL: "true"
  DB_HOST: "CHANGE_ME_DB_HOST"
  DB_NAME: "CHANGE_ME_DB_NAME"
  ALLOWED_ORIGINS: ""
  INTERNAL_BACKEND_URL: "http://backend-service.book-review.svc.cluster.local:5000"